name: Continuous Integration

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install pip and packages
        uses: luisgs7/pip-packages@v1
        
      - name: Run tests with unittest
        run: python -m unittest
